# Generated by Django 4.0.4 on 2022-05-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
