# Generated by Django 4.0.4 on 2022-05-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_userextra_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
